
import curses

REFRESH_DELAY_MS = 100

WHITE = curses.COLOR_WHITE
RED = curses.COLOR_RED
GREEN = curses.COLOR_GREEN
CYAN = curses.COLOR_CYAN
YELLOW = curses.COLOR_YELLOW

COLOR_NORMAL = 1
COLOR_CORRECT = 2
COLOR_WRONG = 3
COLOR_BORDER = 4

PADDING_X = 2
PADDING_Y = 2
